name: Integration Continue

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/

        # Exécuter Pylint sur tous les fichiers Python
      - name: Lint code with Pylint
        run: |
          pip install pylint
          pylint --disable=R,C --fail-under=5 --ignore=Old **/*.py

      - name: Generate Documentation
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build --site-dir=public

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
